FROM node

WORKDIR /usr/src/app

ENV DB_HOST=api-db \
    DB_PORT=5432 \
    DB_DATABASE=db_tournament \
    DB_USERNAME=api \
    DB_PASSWORD=api

COPY package*.json ./

RUN npm install
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y postgresql-client  

COPY docker-entrypoint /usr/local/bin/
RUN sed -i -e 's/\r$//' /usr/local/bin/docker-entrypoint && chmod +x /usr/local/bin/docker-entrypoint
ENTRYPOINT [ "docker-entrypoint" ]

EXPOSE 3000
