version: "3.4"

services:

  api-backend:
    image: node
    build: .
    hostname: backend
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    restart: on-failure:3
    depends_on:
      - api-db

  api-db:
    image: mysql:5.7
    hostname: api-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_visitor
      - MYSQL_USER=api
      - MYSQL_PASSWORD=api
    ports:
      - 1080:3306
    restart: on-failure:3

networks:
  default:
    external:
      name: ${NETWORK:-local}
