# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd backend/ && npm install   
    - run: cd frontend/ && npm install

  test:
    runs-on: ubuntu-latest

    container: node
    
      steps:
        - name: Running docker
        uses:
          runs:
            using: 'docker'
            image: 'Dockerfile'
        - name: CI tests
        run: cd backend
        run: npm ci-test
        
    env:
      CI: true
